# This file is app/nixpacks.toml

# This section tells Nixpacks to install the base language (Python with pip)
# AND the required system libraries for PyMuPDF.
[phases.setup]
nixPkgs = ["pkgs.python311", "pkgs.python311Packages.pip", "pkgs.mupdf"]

# This section explicitly tells Nixpacks how to install your Python libraries.
[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

# This section explicitly defines the command to start your server.
[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"